AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda function that generates a plot.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: function/.
      Description: Call the AWS Lambda API
      Timeout: 20
      MemorySize: 512
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaReadOnlyAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: plot-generator-lib
      Description: Dependencies for the plot generator lambda.
      ContentUri: assets.zip
      CompatibleRuntimes:
        - python3.7
